sonar.organization=guibranco
sonar.projectKey=guibranco_pull-request-ui

sonar.sources=src
sonar.tests=tests
sonar.exclusions=src/vite-env.d.ts,src/main.tsx
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
