name: Infisical secrets check

on:
  workflow_dispatch:
  pull_request:

jobs:
  secrets-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Infisical secrets check
        uses: guibranco/github-infisical-secrets-check-action@73d41075c3b2f2961acbb6125d24cd177fe1b0e3 # v4.1.36
